version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      oclif:
        patterns:
        - '@oclif*'
      dev-dependencies:
        dependency-type: 'development'
      
