name: Pull Requests - SwaggerHub CLI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [ 20.x, 22.x, 24.x ]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test
