name: Release - SwaggerHub CLI on GitHub
on:
  push:
    # Sequence of patterns matched against refs/tags
#      tags:
#        - 'v*' 
      branches:
        - OP-10665
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # fetch all tags
      - name: fetch_tags
        run: |
          git tag --list
          git fetch --prune --unshallow --tags
        id: fetch_tags
        
      # npm install changelog
      - name: run_npm_install_changelog
        run: sudo npm i generate-changelog -g
        id: run_npm_install_changelog

      # Generate a changelog from a tag range, parse and set as outputs.
      - name: generate_tag_range_changelog
        run: | 
          changelog="$(generate-changelog --tag v0.2.4..v0.2.5)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
        id: generate_tag_range_changelog

      # Create release in github
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: SwaggerHub CLI Release ${{ github.ref }}
          body: |
            ${{ steps.generate_tag_range_changelog.outputs.changelog }}
          draft: true # Allow swaggerhub-cli team approve the release notes before making public. 
          prerelease: false
