name: Release - SwaggerHub CLI on GitHub
on:
  # This will be trigger if the PR label == gen_release
#   pull_request:
#     types:
#       - labeled
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Create Release
#    if: github.event.label.name == 'gen_release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # fetch all tags to the github ubuntu node
      - name: fetch_tags
        run: |
          git tag --list
          git fetch --prune --tags
          git tag --list
        id: fetch_tags

      # npm install changelog
      - name: run_npm_install_changelog
        run: sudo npm i generate-changelog -g
        id: run_npm_install_changelog

      # Get current tag and release tag.
      # Release tag comes from package.json.
      # Current tag is the tag prior to release tag.
      - name: generate_tag_vars
        run: |
          version_tag_release="v$(cat package.json | jq --raw-output .version)"
          version_tag_current="$(git describe --abbrev=0 --tags ${version_tag_release}^)"
          tag_diff="${version_tag_release}..${version_tag_current}"
          echo "::set-output name=version_tag_release::$version_tag_release"
          echo "::set-output name=version_tag_current::$version_tag_current"
          echo "::set-output name=tagdiffoutput::${tagdiff}"
          echo "Current:${version_tag_current} / Release:${version_tag_release}"

#      # Basic check to find the new release tag, exit if not found.
#      - name: verify_release_tag_exists
#        run: |
#          git tag --list > /tmp/tag_lst
#          if ! grep ${{ steps.generate_tag_vars.outputs.version_tag_release }} /tmp/tag_lst; then
#            echo "Unable to find tag ${{ steps.generate_tag_vars.outputs.version_tag_release }} from 'git tags'"
#            exit; fi

      # Generate a changelog from a tag range, parse and set as an output.
      # Prior changelog method: changelog="$(generate-changelog --tag ${{ github.event.pull_request.body }} $* --file -)"
      - name: generate_tag_range_changelog
        run: |
          echo ${{ steps.generate_tag_vars.outputs.tagdiffoutput }}
          generate-changelog --tag ${{ steps.generate_tag_vars.outputs.tagdiffoutput }} $* --file - > output_diff
          cat output_diff
          #changelog="$(generate-changelog --tag ${{ steps.generate_tag_vars.outputs.tag_diff_output }} $* --file -)"
          changelog="$(cat output_diff)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
        id: generate_tag_range_changelog

      # Create release in github
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.generate_tag_vars.outputs.version_tag_release }}
          release_name: SwaggerHub CLI Release ${{ steps.generate_tag_vars.outputs.version_tag_release }}
          body: |
            ${{ steps.generate_tag_range_changelog.outputs.changelog }}
          draft: true # Allow swaggerhub-cli team approve the release notes before making public.
          prerelease: false
