name: Release - SwaggerHub CLI on GitHub
on:
  # This will be trigger if the PR label == gen_release 
  pull_request:
    types:
      - labeled
jobs:
  build:
    name: Create Release
    if: github.event.label.name == 'gen_release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # fetch all tags to the github ubuntu node
      - name: fetch_tags
        run: |
          git tag --list
          git fetch --prune --tags
          git tag --list
        id: fetch_tags
        
      # npm install changelog
      - name: run_npm_install_changelog
        run: sudo npm i generate-changelog -g
        id: run_npm_install_changelog

      # Generate a changelog from a tag range, parse and set as outputs.
      - name: generate_tag_range_changelog
        run: | 
          version_tag_release="v$(cat package.json | jq --raw-output .version)"
          version_tag_current="git describe --tags --abbrev=0"
          echo "::set-output name=tag_package_json::$version_tag_release"
          echo "Current:${version_tag_current} / Release:${version_tag_release}"
          #changelog="$(generate-changelog --tag ${{ github.event.pull_request.body }} $* --file -)"
          changelog="$(generate-changelog --tag ${version_tag_current}..${version_tag_release} $* --file -)"
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"
        id: generate_tag_range_changelog

      # Create release in github
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.generate_tag_range_changelog.outputs.tag_package_json }}
          release_name: SwaggerHub CLI Release ${{ steps.generate_tag_range_changelog.outputs.tag_package_json }}
          body: |
            ${{ steps.generate_tag_range_changelog.outputs.changelog }}
          draft: true # Allow swaggerhub-cli team approve the release notes before making public. 
          prerelease: false
